Import Library

In [28]:
pip install pandas

Requirement already satisfied: pandas in d:\dataanalyst\paython\bussinessalalysis\.venv\lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=1.26.0 in d:\dataanalyst\paython\bussinessalalysis\.venv\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\dataanalyst\paython\bussinessalalysis\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\dataanalyst\paython\bussinessalalysis\.venv\lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in d:\dataanalyst\paython\bussinessalalysis\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [29]:
import pandas as pd

In [2]:
df = pd.read_csv('customer_shopping_behaviour.csv')

In [3]:
df.head()

,Customer ID,Age,Item Purchased,Gender,Category,Purchase Amount(USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchased,Payment Method,Frequency of Purchases,Unnamed: 18
0,1,43,Scarf,Female,Accessories,117.00,New York,M,Yellow,Spring,3.7,Yes,2-Day Shipping,No,No,2,Credit Card,Quarterly,NaN
1,2,18,Dress,Female,Clothing,78.11,Los Angeles,L,Pink,Winter,3.4,No,Free Shipping,No,No,2,Debit Card,Annually,NaN
2,3,31,Skirt,Female,Clothing,139.63,Houston,L,Gray,Summer,3.8,No,Express,Yes,Yes,1,Debit Card,Quarterly,NaN
3,4,25,Face Cream,Male,Beauty,145.07,San Diego,XS,Navy,Fall,2.6,No,Express,Yes,Yes,1,Debit Card,Weekly,NaN
4,5,50,Shorts,Female,Clothing,122.43,Chicago,M,Green,Fall,4.5,No,Free Shipping,No,No,1,PayPal,Quarterly,NaN

In [4]:
df.tail()

,Customer ID,Age,Item Purchased,Gender,Category,Purchase Amount(USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchased,Payment Method,Frequency of Purchases,Unnamed: 18
2995,2996,42,Heels,Female,Footwear,121.04,Houston,M,Purple,Fall,3.7,Yes,Free Shipping,No,No,5,PayPal,Monthly,NaN
2996,2997,38,Handbag,Female,Accessories,119.21,Dallas,One Size,Brown,Fall,3.7,No,Next Day Air,No,No,0,Bank Transfer,Monthly,NaN
2997,2998,43,Dress,Non-Binary,Clothing,104.57,Las Vegas,XS,Pink,Summer,2.7,Yes,Free Shipping,No,Yes,5,Credit Card,Weekly,NaN
2998,2999,40,Belt,Female,Accessories,122.90,San Diego,XS,Black,Winter,3.8,No,Free Shipping,No,No,6,Debit Card,Monthly,NaN
2999,3000,22,Phone Case,Female,Electronics,48.36,Dallas,S,Black,Fall,4.6,No,Free Shipping,Yes,Yes,1,Cash,Monthly,NaN

Data Understanding

In [5]:
df.shape

(3000, 19)

In [6]:
df.info

<bound method DataFrame.info of       Customer ID  Age Item Purchased      Gender     Category  \
0               1   43          Scarf      Female  Accessories
1               2   18          Dress      Female     Clothing
2               3   31          Skirt      Female     Clothing
3               4   25     Face Cream        Male       Beauty
4               5   50         Shorts      Female     Clothing
...           ...  ...            ...         ...          ...
2995         2996   42          Heels      Female     Footwear
2996         2997   38        Handbag      Female  Accessories
2997         2998   43          Dress  Non-Binary     Clothing
2998         2999   40           Belt      Female  Accessories
2999         3000   22     Phone Case      Female  Electronics

      Purchase Amount(USD)     Location      Size   Color  Season  \
0                   117.00     New York         M  Yellow  Spring
1                    78.11  Los Angeles         L    Pink  Winter
2                   139.63      Houston         L    Gray  Summer
3                   145.07    San Diego        XS    Navy    Fall
4                   122.43      Chicago         M   Green    Fall
...                    ...          ...       ...     ...     ...
2995                121.04      Houston         M  Purple    Fall
2996                119.21       Dallas  One Size   Brown    Fall
2997                104.57    Las Vegas        XS    Pink  Summer
2998                122.90    San Diego        XS   Black  Winter
2999                 48.36       Dallas         S   Black    Fall

      Review Rating Subscription Status   Shipping Type Discount Applied  \
0               3.7                 Yes  2-Day Shipping               No
1               3.4                  No   Free Shipping               No
2               3.8                  No         Express              Yes
3               2.6                  No         Express              Yes
4               4.5                  No   Free Shipping               No
...             ...                 ...             ...              ...
2995            3.7                 Yes   Free Shipping               No
2996            3.7                  No    Next Day Air               No
2997            2.7                 Yes   Free Shipping               No
2998            3.8                  No   Free Shipping               No
2999            4.6                  No   Free Shipping              Yes

     Promo Code Used  Previous Purchased Payment Method  \
0                 No                   2    Credit Card
1                 No                   2     Debit Card
2                Yes                   1     Debit Card
3                Yes                   1     Debit Card
4                 No                   1         PayPal
...              ...                 ...            ...
2995              No                   5         PayPal
2996              No                   0  Bank Transfer
2997             Yes                   5    Credit Card
2998              No                   6     Debit Card
2999             Yes                   1           Cash

     Frequency of Purchases  Unnamed: 18
0                 Quarterly          NaN
1                  Annually          NaN
2                 Quarterly          NaN
3                    Weekly          NaN
4                 Quarterly          NaN
...                     ...          ...
2995                Monthly          NaN
2996                Monthly          NaN
2997                 Weekly          NaN
2998                Monthly          NaN
2999                Monthly          NaN

[3000 rows x 19 columns]>

In [7]:
df.isnull().sum()

Customer ID                  0
Age                          0
Item Purchased               0
Gender                       0
Category                     0
Purchase Amount(USD)         0
Location                     0
Size                         0
Color                        0
Season                       0
Review Rating                0
Subscription Status          0
Shipping Type                0
Discount Applied             0
Promo Code Used              0
Previous Purchased           0
Payment Method               0
Frequency of Purchases       0
Unnamed: 18               3000
dtype: int64

In [8]:
df.columns

Index(['Customer ID', 'Age', 'Item Purchased', 'Gender', 'Category',
       'Purchase Amount(USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchased',
       'Payment Method', 'Frequency of Purchases', 'Unnamed: 18'],
      dtype='str')

In [9]:
df['Age']

0       43
1       18
2       31
3       25
4       50
        ..
2995    42
2996    38
2997    43
2998    40
2999    22
Name: Age, Length: 3000, dtype: int64

1. Missing value handaling
2. Column Name Rename
3. Ready the Age group

1. Missing value handaling
---------------------------------

In [10]:
df['Category']

0       Accessories
1          Clothing
2          Clothing
3            Beauty
4          Clothing
           ...
2995       Footwear
2996    Accessories
2997       Clothing
2998    Accessories
2999    Electronics
Name: Category, Length: 3000, dtype: str

In [11]:
df['Review Rating']= df.groupby('Category')['Review Rating'].transform(lambda x :x.fillna(x.mean()))

In [13]:
df.isnull().sum()

Customer ID                  0
Age                          0
Item Purchased               0
Gender                       0
Category                     0
Purchase Amount(USD)         0
Location                     0
Size                         0
Color                        0
Season                       0
Review Rating                0
Subscription Status          0
Shipping Type                0
Discount Applied             0
Promo Code Used              0
Previous Purchased           0
Payment Method               0
Frequency of Purchases       0
Unnamed: 18               3000
dtype: int64

2. Colum Name Rename

In [14]:
df.columns

Index(['Customer ID', 'Age', 'Item Purchased', 'Gender', 'Category',
       'Purchase Amount(USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchased',
       'Payment Method', 'Frequency of Purchases', 'Unnamed: 18'],
      dtype='str')

In [12]:
df.columns = df.columns.str.lower()

In [13]:
df.columns

Index(['customer id', 'age', 'item purchased', 'gender', 'category',
       'purchase amount(usd)', 'location', 'size', 'color', 'season',
       'review rating', 'subscription status', 'shipping type',
       'discount applied', 'promo code used', 'previous purchased',
       'payment method', 'frequency of purchases', 'unnamed: 18'],
      dtype='str')

In [14]:
df.columns = df.columns.str.replace(" ","_")

In [15]:
df.columns

Index(['customer_id', 'age', 'item_purchased', 'gender', 'category',
       'purchase_amount(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchased',
       'payment_method', 'frequency_of_purchases', 'unnamed:_18'],
      dtype='str')

In [16]:
df = df.rename(columns={'purchase_amount_(usd)':"purchase_amount"})

In [17]:
df.columns

Index(['customer_id', 'age', 'item_purchased', 'gender', 'category',
       'purchase_amount(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchased',
       'payment_method', 'frequency_of_purchases', 'unnamed:_18'],
      dtype='str')

3. Ready the Age Group.

In [18]:
df["age_group"] = pd.qcut(df['age'],q=4,labels=['Young','Middle','Imediate_Senior','Senior'])

In [19]:
df["age_group"].head()

0    Imediate_Senior
1              Young
2             Middle
3              Young
4             Senior
Name: age_group, dtype: category
Categories (4, str): ['Young' < 'Middle' < 'Imediate_Senior' < 'Senior']

In [23]:
!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in d:\dataanalyst\paython\bussinessalalysis\.venv\lib\site-packages (1.2.3)
Requirement already satisfied: sqlalchemy in d:\dataanalyst\paython\bussinessalalysis\.venv\lib\site-packages (2.1.4)
Requirement already satisfied: typing-extensions>=4.6.0 in d:\dataanalyst\paython\bussinessalalysis\.venv\lib\site-packages (from sqlalchemy) (4.16.0)

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [24]:
from sqlalchemy import create_engine
import urllib.parse

MySQL Connection

In [25]:
username = "root"
password = urllib.parse.quote_plus("KHJr@1955")
host = "127.0.0.1"
port = 3306
database = "PaythonSQL1"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

with engine.connect() as conn:
    print("Connected Successfully!")

Connected Successfully!

In [33]:
df.to_sql(
    "customer",
    con=engine,
    if_exists='replace',
    index=False
)

3000

In [ ]:
df1 = pd.read_sql("select * from customer limit 5" , engine)

In [37]:
df1.head()

,customer_id,age,item_purchased,gender,category,purchase_amount(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchased,payment_method,frequency_of_purchases,unnamed:_18,age_group
0,1,43,Scarf,Female,Accessories,117.00,New York,M,Yellow,Spring,3.7,Yes,2-Day Shipping,No,No,2,Credit Card,Quarterly,None,Imediate_Senior
1,2,18,Dress,Female,Clothing,78.11,Los Angeles,L,Pink,Winter,3.4,No,Free Shipping,No,No,2,Debit Card,Annually,None,Young
2,3,31,Skirt,Female,Clothing,139.63,Houston,L,Gray,Summer,3.8,No,Express,Yes,Yes,1,Debit Card,Quarterly,None,Middle
3,4,25,Face Cream,Male,Beauty,145.07,San Diego,XS,Navy,Fall,2.6,No,Express,Yes,Yes,1,Debit Card,Weekly,None,Young
4,5,50,Shorts,Female,Clothing,122.43,Chicago,M,Green,Fall,4.5,No,Free Shipping,No,No,1,PayPal,Quarterly,None,Senior